name: AplikasiAman
description: aplikasi untuk monitoring iot

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  font_awesome_flutter: ^9.1.0 


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true  # Pastikan ini disetel ke true untuk menggunakan Material Icons

  assets:
    - assets/bg1.png  
    - assets/bg2.png
    - assets/logo.png
    - assets/logo ig.png
    - assets/smart home oke.jpg  

  fonts:
    - family: HammersmithOne  # Tambahkan font custom jika diperlukan untuk teks
      fonts:
        - asset: assets/hammersmith-one/HammersmithOne.ttf
