name: MyApp
description: aplikasi untuk monitoring iot

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  font_awesome_flutter: ^9.1.0 
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true  # Pastikan ini disetel ke true untuk menggunakan Material Icons

  assets:
    - assets/bg1.png  
    - assets/bg2.png
    - assets/Aman .PNG
    - assets/dapur.jpg
    - assets/smart home oke.jpg  

  fonts:
    - family: HammersmithOne  # Tambahkan font custom jika diperlukan untuk teks
      fonts:
        - asset: assets/hammersmith-one/HammersmithOne.ttf
