name: AplikasiAman
description: aplikasi untuk monitoring iot

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
  sdk: flutter
  firebase_core: ^2.10.0
  firebase_auth: ^6.18.0
  google_sign_in: ^6.3.0
  url_launcher: ^6.0.20

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true  # Pastikan ini disetel ke true untuk menggunakan Material Icons

  assets:
    - assets/bg1.png  
    - assets/bg2.png
    - assets/smart home oke.jpg  

  fonts:
    - family: HammersmithOne  # Tambahkan font custom jika diperlukan untuk teks
      fonts:
        - asset: assets/hammersmith-one/HammersmithOne.ttf
