// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdLwixP7s8DzJoIkgMKjtP71KXuefE8hM',
    appId: '1:1036759584405:web:5d5f71355fc6bcd5fd559c',
    messagingSenderId: '1036759584405',
    projectId: 'iot-4f9cc',
    authDomain: 'iot-4f9cc.firebaseapp.com',
    databaseURL: 'https://iot-4f9cc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-4f9cc.appspot.com',
    measurementId: 'G-D3B1B4QFNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM5KE91sWRthCV9FBIIsqwENpT0sUVKh4',
    appId: '1:1036759584405:android:c2fada929c5036a7fd559c',
    messagingSenderId: '1036759584405',
    projectId: 'iot-4f9cc',
    databaseURL: 'https://iot-4f9cc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-4f9cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7dFmfCXKwDkw6oyAJoGcLFDJqn3PxpW8',
    appId: '1:1036759584405:ios:f22587677dec3413fd559c',
    messagingSenderId: '1036759584405',
    projectId: 'iot-4f9cc',
    databaseURL: 'https://iot-4f9cc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-4f9cc.appspot.com',
    iosClientId: '1036759584405-pc6d5l2gli018bff7cqqmi2ocoerbvg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.aman101',
  );

}